project:
  type: book

book:
  title: "Radiology Standards"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/radiology-standards
  site-url: https://radiology-standards-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: DICOM
      chapters: 
        - text: DICOM SR
          href: "contents/DICOM/dicom-sr.qmd"
        - text: DICOM KOS
          href: "contents/DICOM/dicom-kos.qmd"

format:
  html:
    theme:
      light:
        - theme/warm-light.scss
      dark:
        - theme/warm-dark.scss
    toc-depth: 4
    highlight-style:
      light: theme/atom-one-light-warm.theme
      dark: theme/atom-one-dark-warm.theme

freeze: auto
